S5 box169 diegoardila
veilhelm/SharedBoxServer pull request #34
Opened 2020-09-20 00:57 UTC by Diego-Ardila

creating all the email subscribers in the notification controller and adding the status logic to the notification

2020-09-20 22:21 UTC, simonhoyos approved these changes

2020-09-21 14:59 UTC, simonhoyos requested changes

2020-09-21 14:59 UTC, simonhoyos commented on package.json
> +    "dbInit": "C:\\\"Program Files\"\\MongoDB\\Server\\4.2\\bin\\mongod.exe --dbpath=D:/Donaldo/mongodb-data"
Borrar este comando

2020-09-22 16:00 UTC, ldonaldo commented on package.json
> +    "dbInit": "C:\\\"Program Files\"\\MongoDB\\Server\\4.2\\bin\\mongod.exe --dbpath=D:/Donaldo/mongodb-data"
Content updated

2020-09-22 17:55 UTC, simonhoyos approved these changes

2020-09-23 17:12 UTC, merged